// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using languagetutor.Data;

#nullable disable

namespace languagetutor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530090712_AddAiTeacherGenerationSettings")]
    partial class AddAiTeacherGenerationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("languagetutor.Models.AITeacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("maxTokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SupportLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supportLanguage");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("systemPrompt");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SupportLanguage");

                    b.ToTable("AITeacher", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personaName");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Language", "PersonaName");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("isPublished");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.ExamPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("examId");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamPart", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("courseId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.PronunciationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<float>("AccuracyScore")
                        .HasColumnType("real")
                        .HasColumnName("accuracyScore");

                    b.Property<float>("CompletenessScore")
                        .HasColumnType("real")
                        .HasColumnName("completenessScore");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<float>("FluencyScore")
                        .HasColumnType("real")
                        .HasColumnName("fluencyScore");

                    b.Property<float>("OverallScore")
                        .HasColumnType("real")
                        .HasColumnName("overallScore");

                    b.Property<float?>("ProsodyScore")
                        .HasColumnType("real")
                        .HasColumnName("prosodyScore");

                    b.Property<string>("ReferenceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referenceText");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<string>("WordDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("wordDetails");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PronunciationRecord", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text")
                        .HasColumnName("correctAnswer");

                    b.Property<string>("EvalCriteria")
                        .HasColumnType("text")
                        .HasColumnName("evalCriteria");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("groupId");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("ReferenceText")
                        .HasColumnType("text")
                        .HasColumnName("referenceText");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.QuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audioUrl");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageUrl");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("partId");

                    b.Property<string>("Passage")
                        .HasColumnType("text")
                        .HasColumnName("passage");

                    b.Property<string>("SsmlScript")
                        .HasColumnType("text")
                        .HasColumnName("ssmlScript");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("QuestionGroup", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.Score", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionTime")
                        .HasColumnType("integer")
                        .HasColumnName("completionTime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lessonId");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("totalQuestions");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("Score", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endTime");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("examId");

                    b.Property<int?>("ListeningScore")
                        .HasColumnType("integer")
                        .HasColumnName("listeningScore");

                    b.Property<int?>("ReadingScore")
                        .HasColumnType("integer")
                        .HasColumnName("readingScore");

                    b.Property<int?>("SpeakingScore")
                        .HasColumnType("integer")
                        .HasColumnName("speakingScore");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("totalScore");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<int?>("WritingScore")
                        .HasColumnType("integer")
                        .HasColumnName("writingScore");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("TestAttempt", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LanguagePreference")
                        .HasColumnType("text")
                        .HasColumnName("languagePreference");

                    b.Property<string>("LearningGoal")
                        .HasColumnType("text")
                        .HasColumnName("learningGoal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("text")
                        .HasColumnName("skillLevel");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("aiFeedback");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("attemptId");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audioUrl");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("isCorrect");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("questionId");

                    b.Property<float?>("ScoreValue")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<string>("SelectedOption")
                        .HasColumnType("text")
                        .HasColumnName("selectedOption");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("text")
                        .HasColumnName("textAnswer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserAnswer", (string)null);
                });

            modelBuilder.Entity("languagetutor.Models.ChatMessage", b =>
                {
                    b.HasOne("languagetutor.Models.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("languagetutor.Models.ExamPart", b =>
                {
                    b.HasOne("languagetutor.Models.Exam", "Exam")
                        .WithMany("Parts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("languagetutor.Models.Lesson", b =>
                {
                    b.HasOne("languagetutor.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("languagetutor.Models.PronunciationRecord", b =>
                {
                    b.HasOne("languagetutor.Models.User", "User")
                        .WithMany("PronunciationRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("languagetutor.Models.Question", b =>
                {
                    b.HasOne("languagetutor.Models.QuestionGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("languagetutor.Models.QuestionGroup", b =>
                {
                    b.HasOne("languagetutor.Models.ExamPart", "Part")
                        .WithMany("Groups")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("languagetutor.Models.Score", b =>
                {
                    b.HasOne("languagetutor.Models.Lesson", "Lesson")
                        .WithMany("Scores")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("languagetutor.Models.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("languagetutor.Models.TestAttempt", b =>
                {
                    b.HasOne("languagetutor.Models.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("languagetutor.Models.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("languagetutor.Models.UserAnswer", b =>
                {
                    b.HasOne("languagetutor.Models.TestAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("languagetutor.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("languagetutor.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("languagetutor.Models.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("languagetutor.Models.ExamPart", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("languagetutor.Models.Lesson", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("languagetutor.Models.Question", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("languagetutor.Models.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("languagetutor.Models.TestAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("languagetutor.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("PronunciationRecords");

                    b.Navigation("Scores");

                    b.Navigation("TestAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
